version: '3'
services:

  postgres1:
    image: docker.arvancloud.ir/postgres
    container_name: database
    environment:
      POSTGRES_USER: ehsan
      POSTGRES_PASSWORD: ehsan
      POSTGRES_DB: eventdb
    ports:
      - "5432:5432"
    networks:
      - my-network

  #challenge
  challenge-app:
    image: challenge
    container_name: challenge
    ports:
      - "8080:8080"
    #        - "5005:5005"
    #      environment: #for attaching the IDE to the container for debugging
    #        - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    networks:
      - my-network

  adminer:
    image: docker.arvancloud.ir/adminer
    container_name: adminer
    ports:
      - "8090:8080"
    networks:
      - my-network

networks:
  my-network:
    external: true